### ISSUE TITLE
Docker compose simples - Execute com facilidade

### ISSUE THREAD

**Issue by mendoncart** [wppconnect-team/wpp-docker#37]
Não sei porque, os exemplos passam dockerfile ou fazem o build no docker compose...
Resolvi postar isso aqui, porque:

1. Pode ajudar outras pessoas com menos conhecimento a rodar o container com maior facilidade
2. Talvez alguém me dê um porque não fazer assim e fazer conforme os exemplos...

Eu rodo o container através de um docker compose bem simples, que pode ser usado numa stack do portainer facilmente:

``` yaml
version: '3'
services:
  wppconnect-server-cli:
    image: wppconnect/server-cli:latest
    container_name: wppconnect-server-cli
    command: wppserver --secretKey ChaveSecretaAqui --port 21465 --frontend --no-webhook-listenAcks --no-webhook-onPresenceChanged --no-webhook-onParticipantsChanged --webhook-url http://seu.webhook.aqui:123 --webhook-allUnreadOnStart --startAllSession
    ports:
      - "21465:21465"
    volumes:
      - /opt/wppconnect-server/app:/home/node/app
    restart: "unless-stopped"
```

Detalhe que os comandos usados em "command" podem ser encontrados [aqui](https://github.com/wppconnect-team/server-cli/blob/d4113a845119d1445c714e6ad1ab4b0123f3e26e/src/program.js#L22C1-L23C6), da linha 22 à 64.
