### ISSUE TITLE
Processar mensagens não lidas ao iniciar

### ISSUE THREAD

**Issue by mendoncart** [wppconnect-team/wpp-docker#41]
Ei galera!
Eu não sei por que, ou se entendi errado, mas, --webhook-allUnreadOnStart não deveria pegar todas as mensagens não lidas e jogar no webhook?
Mesmo iniciando o container, ele não pega as não lidas.

```
version: '3'
services:
  wppconnect-server-cli:
    image: wppconnect/server-cli:latest
    container_name: wppconnect-server-cli
    command: wppserver --secretKey xxxxxx --port 21465 --no-webhook-listenAcks --no-webhook-onPresenceChanged --no-webhook-onParticipantsChanged --webhook-url http://xxxxxxxxxxxx --webhook-allUnreadOnStart --startAllSession --frontend
    ports:
      - "21465:21465"
    volumes:
      - /opt/wppconnect-server/app_main:/home/node/app
      - /opt/wppconnect-server/userDataDir/app_main:/usr/src/wpp-server/userDataDir
    restart: "unless-stopped"
```
